# Generated by Django 5.2.5 on 2025-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
