# Generated by Django 5.2.5 on 2025-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_task_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, to="task.tag"),
        ),
    ]
