# Generated by Django 5.2.6 on 2025-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_tag_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
